//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import "APListData.h"
#import "PSDJsBridge.h"

@interface H5WebViewController : UIViewController
{

}

@property(readonly, nonatomic) UIWebView *h5WebView;
@property(readonly, nonatomic) UIWebView *webView;
@property(retain, nonatomic) UILabel *webviewDomainLabel;

@end


